services:
  db:
    image: postgres:17
    container_name: postgres-canchas
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpass
      POSTGRES_DB: canchasdb
    volumes:
      - ./backend/db:/docker-entrypoint-initdb.d
    restart: always

  backend:
    build: ./backend
    container_name: backend-canchas
    ports:
      - "3000:3000"
    environment:
      - PGUSER=admin
      - PGPASSWORD=adminpass
      - PGDATABASE=canchasdb
      - PGHOST=db
      - PGPORT=5432
    depends_on:
      - db
    restart: always
